# Generated by Django 3.1.3 on 2021-12-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vType', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, default=5000, max_digits=10)),
            ],
            options={
                'ordering': ['-vType'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.voucher')),
            ],
            options={
                'ordering': ['-ssn'],
            },
        ),
    ]
