# Generated by Django 2.1.7 on 2021-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='voucher_id',
            field=models.CharField(choices=[('PP', '紙本'), ('CC', '信用卡'), ('ET', '電子票劵'), ('MB', '行動支付')], default='PP', max_length=2),
        ),
    ]
