# Generated by Django 2.1.7 on 2021-12-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20211211_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
