# Generated by Django 3.2.9 on 2021-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_auto_20211127_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='pid',
            field=models.CharField(max_length=25),
        ),
    ]
