# Generated by Django 3.1.2 on 2021-12-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_prize_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['amount']},
        ),
    ]
