# Generated by Django 3.1.2 on 2021-12-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_auto_20211208_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'ordering': ['-amount']},
        ),
    ]
